### ISSUE TITLE
Recent Conda package?

### ISSUE THREAD

**Issue by ywu** [msmbuilder/msmbuilder2022#15]
Thanks for maintaining this. The msmbuilder on Conda is so old and incompatible with anything that depends on a more recent version (than 3.8) of Python. I tried to build it with your fork, but got stuck with the following error when I run `python setup.py build` on Ubuntu:
```
 File ".../msmbuilder-dev/lib/python3.11/site-packages/Cython/Compiler/Errors.py", line 178, in error
    raise InternalError(message)
Cython.Compiler.Errors.InternalError: Internal compiler error: 'cy_blas.pyx' not found
```
 `cy_blas.pyx` seems probably gone as far as I can see. I wonder how you managed to build it. Any hints/help appreciated.

**Comment by bojunliu0818** [comment]
Hi @ywu, 
Thanks for raising the issue! Could you try `pip install .` within your msmbuilder2022 local directory and make sure that you have the C compiler on your system? Also, I am going to create a new release and upload wheel packages on pypi this week. After that, the msmbuilder package should be able to be installed via pip from the website.

**Comment by ywu** [comment]
Thanks for hint. Looking forward to the new release. If you can create a Conda release, that would be awesome!

**Comment by bojunliu0818** [comment]
Thanks, hopefully it can be released soon! Yes, there are some issues need to be fixed to use the command line of MSMBuilder with python 3.11. Using python3.10 or 3.9 should fix this problem.

**Comment by bojunliu0818** [comment]
I have just updated the source code, where the bug of command line in python 3.11 should be fixed now. You can download this most recent source code and give a try again. Please let me know if there are any problems!

**Comment by ywu** [comment]
Thank you so much for the fix. It works.

**Comment by ywu** [comment]
But the tests still fail at my end:
```
$ python runtests.py
...
running build_ext
Traceback (most recent call last):
  File "/home/wu/src/msmbuilder2022/setup.py", line 195, in <module>
    setup(name='msmbuilder2022',
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line131, in run
    self.run_command(cmd_name)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
    module_list, module_metadata = create_extension_list(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 859, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 707, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 716, in transitive_merge
    return self.transitive_merge_helper(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 722, in transitive_merge_helper
    deps = extract(node)
           ^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 687, in distutils_info0
    cimports, externs, incdirs = self.cimports_externs_incdirs(filename)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Cython/Utils.py", line 129, in Cython.Utils.cached_method.wrapper
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 574, in cimports_externs_incdirs
    for include in self.included_files(filename):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Cython/Utils.py", line 129, in Cython.Utils.cached_method.wrapper
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 556, in included_files
    include_path = self.context.find_include_file(include, source_file_path=filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Compiler/Main.py", line 299, in find_include_file
    error(pos, "'%s' not found" % filename)
  File "/home/wu/snap/miniconda3/envs/new-msmbuilder-dev/lib/python3.11/site-packages/Cython/Compiler/Errors.py", line 178, in error
    raise InternalError(message)
Cython.Compiler.Errors.InternalError: Internal compiler error: 'cy_blas.pyx' not found

Build failed!
```

**Comment by bojunliu0818** [comment]
I think this is fine. We are not using this script anymore and you have already had msmbuilder installed. You can check the tutorial here http://msmbuilder.org/development/examples/index.html to do some tests in a jupyter notebook.

**Comment by ywu** [comment]
Ah. I see. Thanks again!

**Comment by bojunliu0818** [comment]
No problem! I am going to close this issue if there are no more questions.
