### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'MachAr' when calling msmb -h

### ISSUE THREAD

**Issue by xavgit** [msmbuilder/msmbuilder2022#20]
Hi,
I have installed msmbuilder2022 with the commands on Ubuntu 20.04:
git clone https://github.com/msmbuilder/msmbuilder2022.git
python3 -m pip install ./msmbuilder2022

When I call msmb -h I receive the following:
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/msmb", line 5, in <module>
    from msmbuilder.scripts.msmb import main
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/commands/__init__.py", line 5, in <module>
    from .example_datasets import AlanineDipeptideDatasetCommand
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/commands/example_datasets.py", line 4, in <module>
    from ..example_datasets import (AlanineDipeptide, DoubleWell, QuadWell, FsPeptide,
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/example_datasets/__init__.py", line 3, in <module>
    from .brownian1d import DoubleWell, QuadWell
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/example_datasets/brownian1d.py", line 17, in <module>
    from ..msm import _solve_msm_eigensystem
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/msm/__init__.py", line 7, in <module>
    from .bayes_ratematrix import BayesianContinuousTimeMSM
  File "/home/xxxx/.local/lib/python3.8/site-packages/msmbuilder/msm/bayes_ratematrix.py", line 11, in <module>
    from pyhmc import hmc
  File "/home/xxxx/.local/lib/python3.8/site-packages/pyhmc/__init__.py", line 28, in <module>
    from .autocorr1 import integrated_autocorr1
  File "/home/xxxx/.local/lib/python3.8/site-packages/pyhmc/autocorr1.py", line 6, in <module>
    from statsmodels.tsa.stattools import acf
  File "/home/xxxx/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py", line 16, in <module>
    from statsmodels.regression.linear_model import OLS, yule_walker
  File "/home/xxxx/.local/lib/python3.8/site-packages/statsmodels/regression/__init__.py", line 1, in <module>
    from .linear_model import yule_walker
  File "/home/xxxx/.local/lib/python3.8/site-packages/statsmodels/regression/linear_model.py", line 46, in <module>
    import statsmodels.base.model as base
  File "/home/xxxx/.local/lib/python3.8/site-packages/statsmodels/base/model.py", line 16, in <module>
    from statsmodels.tools.numdiff import approx_fprime
  File "/home/xxxx/.local/lib/python3.8/site-packages/statsmodels/tools/numdiff.py", line 51, in <module>
    EPS = np.MachAr().eps
  File "/home/xxxx/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'MachAr'

Any suggestions? 

Thanks.

Saverio

P.S.On Ubuntu 22.04 there is not the problem.

**Comment by bojunliu0818** [comment]
Hi @xavgit, thanks for reporting the issue! It seems like 'MachAr' has been deprecated since NumPy v1.22, and the recent statsmodels package has updated its code to replace "np.MachAr().eps" with "np.finfo(float).eps". So maybe you could manually try either downgrading your numpy package to version 1.22 or lower, or upgrading your statsmodels package to version 0.14 or higher.

**Comment by xavgit** [comment]
Hi,
upgrading statsmodels to version 0.14 allows the call to msmb -h to 
run without problems.

Thanks.

Saverio

**Comment by bojunliu0818** [comment]
Great, I am going to close the issue.
