### ISSUE TITLE
Which scikit-learn version is compatible with this package?

### ISSUE THREAD

**Issue by hoon-ock** [msmbuilder/msmbuilder2022#6]
I'm experienceing the joblib import error with the recent version of scikit-learn. Even though I downgraded it to 0.22.1 or around, it still returns issues with '_kmedoids' and so on.

ImportError: cannot import name 'joblib' from 'sklearn.externals'

**Comment by bojunliu0818** [comment]
Hi, could you upgrade your scikit-learn version to >=1.02.x and try again? Also, could you provide both your code and the error in detail?

**Comment by hoon-ock** [comment]
It's okay for `import msmbuilder`, but it returns an issue regarding other submodules. 

```
>>> import msmbuilder.cluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/cluster/__init__.py", line 25, in <module>
    from .kmedoids import KMedoids
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/cluster/kmedoids.py", line 17, in <module>
    from . import _kmedoids
ImportError: cannot import name '_kmedoids' from partially initialized module 'msmbuilder.cluster' (most likely due to a circular import) (/home/hoon/boltzmann/msmbuilder2022/msmbuilder/cluster/__init__.py)

```
```
>>> import msmbuilder.example_datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/example_datasets/__init__.py", line 3, in <module>
    from .brownian1d import DoubleWell, QuadWell
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/example_datasets/brownian1d.py", line 17, in <module>
    from ..msm import _solve_msm_eigensystem
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/msm/__init__.py", line 2, in <module>
    from .core import *
  File "/home/hoon/boltzmann/msmbuilder2022/msmbuilder/msm/core.py", line 16, in <module>
    from . import _ratematrix
ImportError: cannot import name '_ratematrix' from partially initialized module 'msmbuilder.msm' (most likely due to a circular import) (/home/hoon/boltzmann/msmbuilder2022/msmbuilder/msm/__init__.py)
```

**Comment by hoon-ock** [comment]
Versions in my environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
blosc                     1.21.0               h4ff587b_1  
bottleneck                1.3.6           py310h0a54255_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7       py310h06a4308_0  
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cryptography              39.0.0          py310h65dfdc0_0    conda-forge
cython                    0.29.32         py310h6a678d5_0  
fastcluster               1.2.6                    pypi_0    pypi
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
joblib                    1.1.1           py310h06a4308_0  
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
libcurl                   7.87.0               h91b91d3_0  
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mdtraj                    1.9.7           py310hd8d60c7_1    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310h7f8727e_0  
mkl_fft                   1.3.1           py310hd6ae3a3_0  
mkl_random                1.2.2           py310h00e6091_0  
msmbuilder2022            3.9.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numexpr                   2.8.4           py310h8879344_0  
numpy                     1.23.5          py310hd5efca6_0  
numpy-base                1.23.5          py310h8e6c178_0  
openssl                   1.1.1s               h7f8727e_0  
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2           py310h1128e8f_0  
pip                       22.3.1          py310h06a4308_0  
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.7.0           py310hf5df6ce_0    conda-forge
python                    3.10.9               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
readline                  8.2                  h5eee18b_0  
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.0           py310h6a678d5_0  
scipy                     1.10.0          py310hd5efca6_0  
setuptools                65.6.3          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlite                    3.40.1               h5082296_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge

```

**Comment by hoon-ock** [comment]
The above error is gone after commenting out `from .kmedoids import KMedoids` under `msmbuilder/cluster/__init__.py`. But, not sure this would impact other loop.

**Comment by bojunliu0818** [comment]
It seems like you install msmbuilder2022 source code locally using pip with python=3.10? 
Probably you can create a new environment with python=3.9 (as we haven't checked compatibility with python=3.10 yet) and using command:
```
conda install -c conda-forge testmsm
Or,
you can clone the source code from github and try:
```
conda config --add channels conda-forge
conda install conda-build jinja2 conda-verify
conda build devtools/conda-recipe
conda install --use-local msmbuilder2022

**Comment by hoon-ock** [comment]
Thanks! 
After commening out `from .kmedoids import KMedoids`, I installed below:
`pip install pyyaml
`conda install -c anaconda jinja2

Then, it seems like passing all test for the modules below even with python3.10. 
```
imports:
    - msmbuilder
    - msmbuilder.cluster
    - msmbuilder.commands
    - msmbuilder.decomposition
    - msmbuilder.example_datasets
    - msmbuilder.feature_extraction
    - msmbuilder.feature_selection
    - msmbuilder.featurizer
    - msmbuilder.hmm
    - msmbuilder.io
    - msmbuilder.libdistance
    - msmbuilder.lumping
    - msmbuilder.msm
    - msmbuilder.preprocessing
    - msmbuilder.scripts
    - msmbuilder.tests
    - msmbuilder.tpt
    - msmbuilder.utils
```

I'll switch back to python 3.9 once I experience some other issues. Thank you very much for the kind explanation.

**Comment by bojunliu0818** [comment]
Sounds good!

**Comment by hoon-ock** [comment]
FYI, it seems like the package is not compatible with python 3.10. msmbuilder.decomposition throws errors: `AttributeError: module 'collections' has no attribute 'Sequence'`. I'll switch back to 3.9

**Comment by bojunliu0818** [comment]
I see, thanks for reporting issue!
